#!/bin/sh

Jdir=`dirname $(readlink -f $0)`
. $Jdir/functions

usage()
{
	echo 'Usage:'
	echo "$0 [create|destroy|rollback] SnapshotName"
	echo "$0 list"
	exit 1
}

if [ -z "$1" ]; then
	usage
fi
reset=false
case "$1" in
	l*) ;;
	*) if [ -z "$2" ]; then
		usage
	   fi
esac
case "$1" in
	r*) jl=`RKjails`
	    if [ -n "$jl" ]; then
		read -p "Some jails are running. Need to shutdown them before. (y/N) " rep
		case "$rep" in
			[yY]*) 	for j in $jl; do
			        	echo -n "Stopping jail $j."
					$Jdir/stop $j	
				done
				reset=true;;
			*) echo "Rollback canceled."
			   return 0;;
		esac
	   fi
esac

MainSnap base $1 $2
if [ $? -ne 0 ]; then
	usage
fi
if $reset; then
	for j in $jl; do
		echo "Starting jail $j."	
		$Jdir/start $j > /dev/null
	done
fi