#!/bin/sh

Jdir=`dirname $(readlink -f $0)`

# Source common functions
. $Jdir/functions

release=$1
TestFBV $release

# Test if the host is equal or superior to the requested release
TestRelOk $release

echo 'Delete previous base snapshot "Ok" if any, and create a new one.'
MainSnap base destroy ok > /dev/null 2>&1
MainSnap base create ok

ver=`$Jdir/base/bin/freebsd-version -u`
MNI=$(echo $ver | cut -d . -f 1)
MNR=$(echo $release | cut -d . -f 1)

env PAGER="/bin/cat" env UNAME_r=$ver freebsd-update -b $Jdir/base \
 -d $Jdir/base/var/db/freebsd-update -f $Jdir/base/etc/freebsd-update.conf \
 -r $release upgrade install
TestErr "Error during upgrade or first install" $?
freebsd-update -b $Jdir/base -d $Jdir/base/var/db/freebsd-update \
 -f $Jdir/base/etc/freebsd-update.conf install
TestErr "Error during upgrade second install" $?

jl=`RKjails`
echo
echo 'Warning! Only the currently running jails will be properly upgraded.'
echo "These jails are: $jl."
echo "Note the list of kjail startup jails: $jails_list."
echo 'If there are some others jails to upgrade, open a new CLI and start them before to proceed!'
read -p 'Press enter when ready.' rep
echo

jl=`RKjails`
for j in $jl; do
	echo "Delete previous jail snapshot $jail@ok if any, and create a new one."
	MainSnap jail destroy $j ok > /dev/null 2>&1
	MainSnap jail create $j ok
	echo "Restart jail $j..."
	$Jdir/restart $j > /dev/null
done

if [ "$MNI" != "$MNR" ]; then
	echo
	echo '-------------------------------'
	echo 'Major release upgrade detected.'
	echo '-------------------------------'
	
	for j in $jl; do
		echo "Reinstalling packages for jail $j..."	
		jexec $j /usr/local/sbin/pkg-static upgrade -fy
		jexec $j /usr/local/sbin/pkg-static autoremove -y	
	done
	freebsd-update -b $Jdir/base -d $Jdir/base/var/db/freebsd-update \
 -f $Jdir/base/etc/freebsd-update.conf install
fi

for j in $jl; do
	echo "Merging config files for Jail $j..."
	jexec $j /usr/sbin/etcupdate diff > /dev/null
	jexec $j /usr/sbin/etcupdate > /dev/null
	jexec $j /usr/sbin/etcupdate resolve
	echo "Restart jail $j..."	
	$Jdir/restart $j > /dev/null
done
	
echo '*** Base upgrade completed. ***'


	